services:
  otel-collector:
    image: otel/opentelemetry-collector:0.109.0
    restart: always
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./docker/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector http://localhost:8888/metrics
      - "8889:8889" # Prometheus exporter metrics http://localhost:8889/metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension


  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    user: root
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml  # Keep your Tempo configuration file
      - ./tempoData:/tmp/tempo  # Persist data in the /tempoData directory
    ports:
      - "3200:3200"   # Tempo UI and query endpoint
      - "1111:4317"   # OTLP gRPC receiver
      - "1112:4318"   # OTLP HTTP receiver
  loki:
    image: grafana/loki:2.8.0
    user: root
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki-local-config.yaml:/etc/loki/local-config.yaml
      - ./lokiData:/tmp/loki  # Persist data in the /lokiData directory
    ports:
      - "3100:3100" # Loki query endpoint
      - "1114:4317"   # OTLP gRPC receiver
      - "1113:4318"   # OTLP HTTP receiver


  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./docker/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - ./storage/logs:/logs
    command:
      - -config.file=/etc/promtail/config.yaml


  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000" # http://localhost:3000/explore