receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
  memory_limiter:
    limit_mib: 4000
    spike_limit_mib: 500
    check_interval: 1s

exporters:
  # Tempo exporter (OTLP gRPC)
  otlp/tempo:
    endpoint: "localhost:4317"  # Ensure this points to Tempo's gRPC receiver
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel_collector"

  # Loki exporter for logs (OTLP HTTP)
  otlp/loki:
    endpoint: "localhost:4318"  # Ensure this points to Loki's HTTP receiver
    tls:
      insecure: true

  # Logging exporter for debugging trace processing
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, logging]  # Add logging to see trace activity

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/loki]  # Add Loki exporter to logs pipeline
